services:
  mongodb:
    image: mongo:7
    container_name: uneg_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: uneg_bienes
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: uneg_api
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=uneg_bienes
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2

  ollama:
    image: ollama/ollama:latest
    container_name: uneg_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  frontend:
    build: ./frontend-uneg
    container_name: uneg_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data:
  ollama_data: