// Seed completo: bienes, movimientos, desincorporaciones
// Usa new Date() nativo de MongoDB

const bienes = [
  {codigo_inventario:"UNEG-ATL-03-00001", codigo_sudebip:"1.03.01.01", grupo_sudebip:"Equipos de Computacion", descripcion:"Computadora de escritorio Dell OptiPlex 7090", marca:"Dell", modelo:"OptiPlex 7090", serial:"DL-2024-001", valor_adquisicion:850.00, fecha_adquisicion:new Date("2023-03-15"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 2, Oficina 201", responsable:"Maria Garcia", cedula_responsable:"V-15234567", departamento:"Administracion", created_at:new Date("2023-03-15"), updated_at:new Date("2023-03-15")},
  {codigo_inventario:"UNEG-ATL-03-00002", codigo_sudebip:"1.03.01.01", grupo_sudebip:"Equipos de Computacion", descripcion:"Computadora de escritorio HP ProDesk 400", marca:"HP", modelo:"ProDesk 400 G7", serial:"HP-2024-002", valor_adquisicion:720.00, fecha_adquisicion:new Date("2023-05-20"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Academico, Laboratorio 3", responsable:"Carlos Rodriguez", cedula_responsable:"V-18456789", departamento:"Coordinacion de Informatica", created_at:new Date("2023-05-20"), updated_at:new Date("2023-05-20")},
  {codigo_inventario:"UNEG-VAS-03-00003", codigo_sudebip:"1.03.01.01", grupo_sudebip:"Equipos de Computacion", descripcion:"Computadora de escritorio Lenovo ThinkCentre", marca:"Lenovo", modelo:"ThinkCentre M70q", serial:"LN-2023-015", valor_adquisicion:680.00, fecha_adquisicion:new Date("2022-11-10"), estado:"EN_USO", condicion:"REGULAR", sede:{codigo:"VAS",nombre:"Sede Villa Asia"}, ubicacion_especifica:"Oficina de Registro, Planta Baja", responsable:"Ana Martinez", cedula_responsable:"V-20123456", departamento:"Registro Academico", created_at:new Date("2022-11-10"), updated_at:new Date("2022-11-10")},
  {codigo_inventario:"UNEG-ATL-03-00004", codigo_sudebip:"1.03.01.02", grupo_sudebip:"Equipos de Computacion", descripcion:"Laptop HP EliteBook 840 G8", marca:"HP", modelo:"EliteBook 840 G8", serial:"HP-LAP-2024-001", valor_adquisicion:1200.00, fecha_adquisicion:new Date("2024-01-10"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Decanato, Oficina del Decano", responsable:"Prof. Juan Hernandez", cedula_responsable:"V-12345678", departamento:"Decanato de Ingenieria", created_at:new Date("2024-01-10"), updated_at:new Date("2024-01-10")},
  {codigo_inventario:"UNEG-JBO-03-00005", codigo_sudebip:"1.03.01.02", grupo_sudebip:"Equipos de Computacion", descripcion:"Laptop Dell Latitude 5520", marca:"Dell", modelo:"Latitude 5520", serial:"DL-LAP-2023-008", valor_adquisicion:950.00, fecha_adquisicion:new Date("2023-08-22"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"JBO",nombre:"Sede Jose Bolivar"}, ubicacion_especifica:"Biblioteca Central, Sala de Profesores", responsable:"Luisa Perez", cedula_responsable:"V-14567890", departamento:"Biblioteca", created_at:new Date("2023-08-22"), updated_at:new Date("2023-08-22")},
  {codigo_inventario:"UNEG-ATL-03-00006", codigo_sudebip:"1.03.02.01", grupo_sudebip:"Equipos de Computacion", descripcion:"Monitor Samsung 24 pulgadas LED", marca:"Samsung", modelo:"S24R350", serial:"SM-MON-2024-003", valor_adquisicion:180.00, fecha_adquisicion:new Date("2023-03-15"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 2, Oficina 201", responsable:"Maria Garcia", cedula_responsable:"V-15234567", departamento:"Administracion", created_at:new Date("2023-03-15"), updated_at:new Date("2023-03-15")},
  {codigo_inventario:"UNEG-VAS-03-00007", codigo_sudebip:"1.03.02.01", grupo_sudebip:"Equipos de Computacion", descripcion:"Monitor LG 27 pulgadas IPS", marca:"LG", modelo:"27MK430H", serial:"LG-MON-2023-007", valor_adquisicion:220.00, fecha_adquisicion:new Date("2023-06-01"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"VAS",nombre:"Sede Villa Asia"}, ubicacion_especifica:"Laboratorio de Diseno, Piso 1", responsable:"Pedro Sanchez", cedula_responsable:"V-19876543", departamento:"Coordinacion de Diseno", created_at:new Date("2023-06-01"), updated_at:new Date("2023-06-01")},
  {codigo_inventario:"UNEG-ATL-03-00008", codigo_sudebip:"1.03.02.02", grupo_sudebip:"Equipos de Computacion", descripcion:"Impresora HP LaserJet Pro M404dn", marca:"HP", modelo:"LaserJet Pro M404dn", serial:"HP-IMP-2023-004", valor_adquisicion:350.00, fecha_adquisicion:new Date("2023-02-28"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 1, Sala de Copiado", responsable:"Rosa Diaz", cedula_responsable:"V-16789012", departamento:"Administracion", created_at:new Date("2023-02-28"), updated_at:new Date("2023-02-28")},
  {codigo_inventario:"UNEG-CHI-03-00009", codigo_sudebip:"1.03.02.02", grupo_sudebip:"Equipos de Computacion", descripcion:"Impresora Epson EcoTank L3250", marca:"Epson", modelo:"EcoTank L3250", serial:"EP-IMP-2022-011", valor_adquisicion:250.00, fecha_adquisicion:new Date("2022-09-15"), estado:"INSERVIBLE", condicion:"MALO", sede:{codigo:"CHI",nombre:"Sede Chilemex"}, ubicacion_especifica:"Oficina de Coordinacion, Planta Baja", responsable:"Miguel Torres", cedula_responsable:"V-17654321", departamento:"Coordinacion de Extension", created_at:new Date("2022-09-15"), updated_at:new Date("2022-09-15")},
  {codigo_inventario:"UNEG-ATL-02-00010", codigo_sudebip:"1.02.01.01", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Escritorio ejecutivo de madera con gavetas", marca:"Muebles Venezuela", modelo:"EJ-200", serial:"MV-ESC-2020-001", valor_adquisicion:280.00, fecha_adquisicion:new Date("2020-06-10"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Decanato, Oficina del Decano", responsable:"Prof. Juan Hernandez", cedula_responsable:"V-12345678", departamento:"Decanato de Ingenieria", created_at:new Date("2020-06-10"), updated_at:new Date("2020-06-10")},
  {codigo_inventario:"UNEG-VAS-02-00011", codigo_sudebip:"1.02.01.01", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Escritorio secretarial metalico", marca:"Ofimuebles", modelo:"SEC-100", serial:"OF-ESC-2019-015", valor_adquisicion:150.00, fecha_adquisicion:new Date("2019-03-22"), estado:"EN_USO", condicion:"REGULAR", sede:{codigo:"VAS",nombre:"Sede Villa Asia"}, ubicacion_especifica:"Oficina de Registro, Planta Baja", responsable:"Ana Martinez", cedula_responsable:"V-20123456", departamento:"Registro Academico", created_at:new Date("2019-03-22"), updated_at:new Date("2019-03-22")},
  {codigo_inventario:"UNEG-JBO-02-00012", codigo_sudebip:"1.02.01.01", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Escritorio de trabajo en L", marca:"Ofimuebles", modelo:"TL-300", serial:"OF-ESC-2021-022", valor_adquisicion:320.00, fecha_adquisicion:new Date("2021-01-15"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"JBO",nombre:"Sede Jose Bolivar"}, ubicacion_especifica:"Coordinacion de Postgrado, Piso 2", responsable:"Dra. Carmen Lopez", cedula_responsable:"V-11234567", departamento:"Postgrado", created_at:new Date("2021-01-15"), updated_at:new Date("2021-01-15")},
  {codigo_inventario:"UNEG-ATL-02-00013", codigo_sudebip:"1.02.01.02", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Silla ejecutiva ergonomica con apoyabrazos", marca:"ErgoSit", modelo:"PRO-500", serial:"ES-SIL-2023-001", valor_adquisicion:180.00, fecha_adquisicion:new Date("2023-04-05"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Decanato, Oficina del Decano", responsable:"Prof. Juan Hernandez", cedula_responsable:"V-12345678", departamento:"Decanato de Ingenieria", created_at:new Date("2023-04-05"), updated_at:new Date("2023-04-05")},
  {codigo_inventario:"UNEG-CHI-02-00014", codigo_sudebip:"1.02.01.02", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Silla de oficina giratoria negra", marca:"GeneriMueble", modelo:"OFC-200", serial:"GM-SIL-2020-033", valor_adquisicion:85.00, fecha_adquisicion:new Date("2020-08-12"), estado:"DESINCORPORADO", condicion:"MALO", sede:{codigo:"CHI",nombre:"Sede Chilemex"}, ubicacion_especifica:"Sala de Reuniones, Piso 1", responsable:"Roberto Blanco", cedula_responsable:"V-13456789", departamento:"Coordinacion de Extension", created_at:new Date("2020-08-12"), updated_at:new Date("2024-10-05")},
  {codigo_inventario:"UNEG-ATL-04-00015", codigo_sudebip:"1.04.01.01", grupo_sudebip:"Equipos de Comunicacion", descripcion:"Videoproyector Epson PowerLite E20", marca:"Epson", modelo:"PowerLite E20", serial:"EP-PRO-2023-002", valor_adquisicion:450.00, fecha_adquisicion:new Date("2023-07-18"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Auditorio Principal", responsable:"Jose Ramirez", cedula_responsable:"V-16234567", departamento:"Servicios Generales", created_at:new Date("2023-07-18"), updated_at:new Date("2023-07-18")},
  {codigo_inventario:"UNEG-VAS-04-00016", codigo_sudebip:"1.04.01.01", grupo_sudebip:"Equipos de Comunicacion", descripcion:"Videoproyector ViewSonic PA503S", marca:"ViewSonic", modelo:"PA503S", serial:"VS-PRO-2021-006", valor_adquisicion:380.00, fecha_adquisicion:new Date("2021-11-25"), estado:"EN_USO", condicion:"REGULAR", sede:{codigo:"VAS",nombre:"Sede Villa Asia"}, ubicacion_especifica:"Sala de Conferencias B", responsable:"Pedro Sanchez", cedula_responsable:"V-19876543", departamento:"Coordinacion de Diseno", created_at:new Date("2021-11-25"), updated_at:new Date("2021-11-25")},
  {codigo_inventario:"UNEG-ATL-05-00017", codigo_sudebip:"1.05.01.01", grupo_sudebip:"Equipos de Climatizacion", descripcion:"Aire acondicionado split 12000 BTU", marca:"Samsung", modelo:"AR12BSHQAWKNAZ", serial:"SM-AC-2022-004", valor_adquisicion:550.00, fecha_adquisicion:new Date("2022-04-10"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 2", responsable:"Jose Ramirez", cedula_responsable:"V-16234567", departamento:"Servicios Generales", created_at:new Date("2022-04-10"), updated_at:new Date("2022-04-10")},
  {codigo_inventario:"UNEG-JBO-05-00018", codigo_sudebip:"1.05.01.01", grupo_sudebip:"Equipos de Climatizacion", descripcion:"Aire acondicionado split 18000 BTU", marca:"LG", modelo:"S4-Q18KL3QA", serial:"LG-AC-2020-009", valor_adquisicion:750.00, fecha_adquisicion:new Date("2020-01-20"), estado:"EN_REPARACION", condicion:"REGULAR", sede:{codigo:"JBO",nombre:"Sede Jose Bolivar"}, ubicacion_especifica:"Biblioteca Central, Sala Principal", responsable:"Luisa Perez", cedula_responsable:"V-14567890", departamento:"Biblioteca", created_at:new Date("2020-01-20"), updated_at:new Date("2024-08-01")},
  {codigo_inventario:"UNEG-ATL-02-00019", codigo_sudebip:"1.02.01.03", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Archivador metalico 4 gavetas", marca:"ArchiVen", modelo:"AM-400", serial:"AV-ARC-2018-007", valor_adquisicion:120.00, fecha_adquisicion:new Date("2018-05-30"), estado:"EN_USO", condicion:"REGULAR", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 1, Archivo", responsable:"Rosa Diaz", cedula_responsable:"V-16789012", departamento:"Administracion", created_at:new Date("2018-05-30"), updated_at:new Date("2018-05-30")},
  {codigo_inventario:"UNEG-ATL-07-00020", codigo_sudebip:"1.07.01.01", grupo_sudebip:"Equipos de Seguridad", descripcion:"Camara de seguridad IP Hikvision 2MP", marca:"Hikvision", modelo:"DS-2CD1023G0E", serial:"HK-CAM-2023-012", valor_adquisicion:95.00, fecha_adquisicion:new Date("2023-09-01"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Entrada Principal, Caseta de Vigilancia", responsable:"Jose Ramirez", cedula_responsable:"V-16234567", departamento:"Seguridad", created_at:new Date("2023-09-01"), updated_at:new Date("2023-09-01")},
  {codigo_inventario:"UNEG-ATL-02-00021", codigo_sudebip:"1.02.03.01", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Pupitre universitario con paleta derecha", marca:"MobEscolar", modelo:"PU-100", serial:null, valor_adquisicion:45.00, fecha_adquisicion:new Date("2019-02-15"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Academico, Aula 101", responsable:"Carlos Rodriguez", cedula_responsable:"V-18456789", departamento:"Coordinacion de Informatica", created_at:new Date("2019-02-15"), updated_at:new Date("2019-02-15")},
  {codigo_inventario:"UNEG-VAS-02-00022", codigo_sudebip:"1.02.03.01", grupo_sudebip:"Mobiliario y Equipos de Oficina", descripcion:"Pupitre universitario con paleta derecha", marca:"MobEscolar", modelo:"PU-100", serial:null, valor_adquisicion:45.00, fecha_adquisicion:new Date("2019-02-15"), estado:"EN_USO", condicion:"REGULAR", sede:{codigo:"VAS",nombre:"Sede Villa Asia"}, ubicacion_especifica:"Aula Magna, Planta Baja", responsable:"Pedro Sanchez", cedula_responsable:"V-19876543", departamento:"Coordinacion de Diseno", created_at:new Date("2019-02-15"), updated_at:new Date("2019-02-15")},
  {codigo_inventario:"UNEG-ATL-08-00023", codigo_sudebip:"1.08.01.01", grupo_sudebip:"Otros Bienes Muebles", descripcion:"Dispensador de agua fria/caliente", marca:"Avanti", modelo:"WD363P", serial:"AV-DIS-2023-003", valor_adquisicion:120.00, fecha_adquisicion:new Date("2023-06-15"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Edificio Administrativo, Piso 1, Recepcion", responsable:"Rosa Diaz", cedula_responsable:"V-16789012", departamento:"Administracion", created_at:new Date("2023-06-15"), updated_at:new Date("2023-06-15")},
  {codigo_inventario:"UNEG-JBO-08-00024", codigo_sudebip:"1.08.01.01", grupo_sudebip:"Otros Bienes Muebles", descripcion:"Microondas Samsung 1.1 pies cubicos", marca:"Samsung", modelo:"MS32J5133AT", serial:"SM-MIC-2022-005", valor_adquisicion:85.00, fecha_adquisicion:new Date("2022-12-01"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"JBO",nombre:"Sede Jose Bolivar"}, ubicacion_especifica:"Comedor Universitario", responsable:"Luisa Perez", cedula_responsable:"V-14567890", departamento:"Bienestar Estudiantil", created_at:new Date("2022-12-01"), updated_at:new Date("2022-12-01")},
  {codigo_inventario:"UNEG-ATL-03-00025", codigo_sudebip:"1.03.03.02", grupo_sudebip:"Equipos de Computacion", descripcion:"Switch Cisco Catalyst 24 puertos", marca:"Cisco", modelo:"C9200L-24T-4G", serial:"CS-SW-2023-001", valor_adquisicion:1800.00, fecha_adquisicion:new Date("2023-10-05"), estado:"EN_USO", condicion:"BUENO", sede:{codigo:"ATL",nombre:"Sede Atlantico"}, ubicacion_especifica:"Data Center, Rack Principal", responsable:"Carlos Rodriguez", cedula_responsable:"V-18456789", departamento:"Coordinacion de Informatica", created_at:new Date("2023-10-05"), updated_at:new Date("2023-10-05")},
];

db.bienes.insertMany(bienes);
print("[OK] " + bienes.length + " bienes insertados");

// Movimientos
const ids = db.bienes.find({},{_id:1}).toArray().map(d=>d._id);
db.movimientos.insertMany([
  {bien_id:ids[3], tipo:"ENTRADA", fecha:new Date("2024-01-10"), sede_origen:null, sede_destino:"ATL", motivo:"Incorporacion de laptop nueva por compra directa", autorizado_por:"Dir. Administracion", documento_soporte:"OC-2024-001", bien_codigo_inventario:"UNEG-ATL-03-00004", bien_descripcion:"Laptop HP EliteBook 840 G8"},
  {bien_id:ids[4], tipo:"ENTRADA", fecha:new Date("2023-08-22"), sede_origen:null, sede_destino:"JBO", motivo:"Incorporacion de laptop para Biblioteca Central", autorizado_por:"Dir. Administracion", documento_soporte:"OC-2023-045", bien_codigo_inventario:"UNEG-JBO-03-00005", bien_descripcion:"Laptop Dell Latitude 5520"},
  {bien_id:ids[0], tipo:"TRASLADO", fecha:new Date("2024-06-15"), sede_origen:"VAS", sede_destino:"ATL", motivo:"Reasignacion a nueva oficina administrativa", autorizado_por:"Jefe de Bienes", documento_soporte:"MEM-2024-012", bien_codigo_inventario:"UNEG-ATL-03-00001", bien_descripcion:"Computadora Dell OptiPlex 7090"},
  {bien_id:ids[2], tipo:"REASIGNACION", fecha:new Date("2024-03-10"), sede_origen:"VAS", sede_destino:"VAS", motivo:"Cambio de custodio por rotacion de personal", autorizado_por:"Coord. Registro", documento_soporte:"MEM-2024-008", bien_codigo_inventario:"UNEG-VAS-03-00003", bien_descripcion:"Computadora Lenovo ThinkCentre"},
  {bien_id:ids[24], tipo:"ENTRADA", fecha:new Date("2023-10-05"), sede_origen:null, sede_destino:"ATL", motivo:"Adquisicion de equipamiento de red para data center", autorizado_por:"Dir. Administracion", documento_soporte:"OC-2023-089", bien_codigo_inventario:"UNEG-ATL-03-00025", bien_descripcion:"Switch Cisco Catalyst 24 puertos"},
  {bien_id:ids[14], tipo:"TRASLADO", fecha:new Date("2024-02-20"), sede_origen:"ATL", sede_destino:"VAS", motivo:"Traslado de proyector para evento academico", autorizado_por:"Coord. Academica", documento_soporte:"MEM-2024-005", bien_codigo_inventario:"UNEG-ATL-04-00015", bien_descripcion:"Videoproyector Epson PowerLite E20"},
  {bien_id:ids[8], tipo:"SALIDA", fecha:new Date("2024-09-01"), sede_origen:"CHI", sede_destino:null, motivo:"Retiro para diagnostico en taller externo", autorizado_por:"Jefe de Bienes", documento_soporte:"MEM-2024-031", bien_codigo_inventario:"UNEG-CHI-03-00009", bien_descripcion:"Impresora Epson EcoTank L3250"}
]);
print("[OK] 7 movimientos insertados");

// Desincorporaciones
db.desincorporaciones.insertMany([
  {bien_id:ids[8], motivo:"INSERVIBILIDAD", justificacion_tecnica:"La impresora Epson EcoTank L3250 presenta fallo total del cabezal de impresion. Se realizaron dos intentos de reparacion sin exito. El costo de reemplazo supera el 70% del valor del equipo.", estado_proceso:"EN_REVISION", solicitado_por:"Miguel Torres", fecha_solicitud:new Date("2024-09-15"), validacion_ia:{cumple_criterios:true, observaciones:"Cumple criterios SUDEBIP"}, aprobado_por:null, fecha_aprobacion:null, bien_codigo_inventario:"UNEG-CHI-03-00009"},
  {bien_id:ids[13], motivo:"OBSOLESCENCIA", justificacion_tecnica:"Silla de oficina con desgaste severo en mecanismo hidraulico y base de ruedas. Tapizado deteriorado. Mas de 4 anos de uso, no justifica reparacion.", estado_proceso:"APROBADA", solicitado_por:"Roberto Blanco", fecha_solicitud:new Date("2024-08-20"), validacion_ia:{cumple_criterios:true, observaciones:"Cumple criterios SUDEBIP"}, aprobado_por:"Jefe de Bienes Nacionales", fecha_aprobacion:new Date("2024-10-05"), bien_codigo_inventario:"UNEG-CHI-02-00014"}
]);
print("[OK] 2 desincorporaciones insertadas");

print("=== RESUMEN ===");
print("Bienes: " + db.bienes.countDocuments());
print("Movimientos: " + db.movimientos.countDocuments());
print("Desincorporaciones: " + db.desincorporaciones.countDocuments());
